### ISSUE TITLE
Dependency checks and FileNotFoundError

### ISSUE THREAD

**Issue by Priyansh2** [Yale-LILY/TutorialBank#1]
Thank you for this needed work for the community. I tried to download data as instructed and found some bugs. The paths in the scripts are not dynamic and it creates `FileNotFoundError`. Please fix this. I also found that the script uses "lynx" as dependency but there is not checks regarding it in the script. Please fix this or add this point in the documentation.

**Comment by Alex-Fabbri** [comment]
Thank you for your interest in the corpus and for pointing out the lynx dependency. I added a note about that in the README. Could you please be more specific about where you are running into errors? I just tried running the scripts on a small sample and didn't run into any errors. 
Thanks!

**Comment by Priyansh2** [comment]
@Alex-Fabbri The error occured because of "lynx" i guess. Moreover I ran the script from inside `src` directory and it gave me the error. I fixed that no issues now.

**Comment by Alex-Fabbri** [comment]
Great, let me know if anything else comes up!
